services:
  - type: web
    name: vintage-tag-analyzer
    env: docker
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: XAI_API_KEY
        sync: false 