services:
  - type: web
    name: vintage-tag-analyzer
    env: python
    pythonVersion: '3.11'
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 120 app:app"
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: XAI_API_KEY
        sync: false 